[package]
name = "Unprivileged Async Ping"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
futures = "0.3"
static_assertions = "1.1.0"

[target.'cfg(windows)'.dependencies.windows]
version = "0.54.0"
features = [
    "Win32_Foundation",
    "Win32_Networking_WinSock",
    "Win32_NetworkManagement_IpHelper",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
]

[target.'cfg(any(target_os = "macos", target_os = "linux"))'.dependencies]
byteorder = "1.0"
ippacket = "0.1"
rand = "0.8"
socket2 = "0.5.6"
tokio = { version = "1.36", features = ["macros", "net", "rt", "time"] }

[dev-dependencies]
tokio = { version = "1.36", features = ["macros", "rt-multi-thread", "time"] }
tokio-stream = { version = "0.1", features = ["time"] }
